### ISSUE TITLE
Make Paddle More responsive

### ISSUE THREAD

**Issue by VRamazing** [igameproject/Breakout#1]
The paddle movement is a bit jerky and it moves after pressing for a while.Make it more reponsive

**Comment by Jaernbrand** [comment]
I can give this one a try.

**Comment by RobinLivesey** [comment]
I've also made a pull request. It looked like a good first issue for me

**Comment by FilipAndersson245** [comment]
emm i tryed doing more responsive paddle but seem im to late to the party should i still do a pull request of my code? (first timer)

**Comment by VRamazing** [comment]
@Jaernbrand has already submited the PR and it has been accepted.I will be closing this issue.Thanks a lot guys.
