### ISSUE TITLE
Add Screenshot and How to Play on Read me

### ISSUE THREAD

**Issue by VRamazing** [igameproject/Breakout#19]
Make sure you are uploading image to github repo and then using that url.

**Comment by cogwizzle** [comment]
I can complete this task.  Can I make a pull request for this?

**Comment by cogwizzle** [comment]
So I am not sure if this has been completed yet, but I just put my merge request in.

**Comment by VRamazing** [comment]
I am sorry @jfehrman  this issue has been completed
