### ISSUE TITLE
Make ball into motion using mouse click and not space bar.

### ISSUE THREAD

**Issue by VRamazing** [igameproject/Breakout#25]
When the game starts we should use mouse click instead of spacebar.This would add intuitive sense and consistency.

**Comment by VRamazing** [comment]
@onslowS You can take this issue if you are interested.Just assign yourself if you are.

**Comment by smtpandey3** [comment]
I will try this one.

**Comment by shalithasuranga** [comment]
I am also trying this 

Thanks
