### ISSUE TITLE
Add More Levels

### ISSUE THREAD

**Issue by VRamazing** [igameproject/Breakout#34]
Each level is a 1-dimensional matrix which is displayed into 2-dimensional form.
Here 3 denotes brick which can be hit 3 times, 2 denotes 2 times and so on.0 denotes empty space.
              [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
               0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
               0,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,
               0,2,2,2,2,2,2,2,2,2,2,2,2,2,3,0,
               0,0,0,0,0,0,0,0,0,0,0,0,0,2,3,0,
               0,0,0,0,0,0,0,0,0,0,0,0,0,2,3,0,
               0,0,0,0,0,0,0,0,0,0,0,0,0,2,3,0,
               0,2,1,0,0,0,0,0,0,0,0,0,0,2,3,0,
               0,2,1,0,0,0,0,0,0,0,0,0,0,2,3,0,
               0,2,1,1,1,1,1,1,1,1,1,1,1,2,3,0,
               0,2,2,2,2,2,2,2,2,2,2,2,2,2,3,0,
               0,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,ows are to your creativity.
               ],

All you have to do is append the levels array in levels.js with new pattern of your interest.Follow the same convention as above.It provides better readability

Please make sure you don't change first 2 rows of zeros.They provide necessary padding.The rest of the
rows are up to you.You can add more bricks rows if you want.

When you go through the levels.js find you will see comments that denote level name to provide a better understanding of how the particular level looks.It's not necessary to follow the same convention but if you are creating an alphabet in the level please follow it.Else give the level your name or some other cool name that defines it in a word.

**Comment by KayvanMazaheri** [comment]
I would like to work on this.  
Is there any specific requirement about how each level should look like?

**Comment by VRamazing** [comment]
No its all upto you.Check how previous levels are designed by updating levels attribute in stage.js to get an idea.
